server:
  port: 8083
  
spring:   
  application:
    name:  cust-service
  
eureka:
  instance:
     leaseRenewalIntervalInSeconds: 1
     leaseExpirationDurationInSeconds:  3
     
  client:
    serviceUrl:
      defaultZone : http://localhost:8085/eureka
      
